### ISSUE TITLE
Scientific Notation

### ISSUE THREAD

**Issue by OliverBalfour** [droptable/javascript-shunting-yard#1]
When you have a number too big for the parser it will give you scientific notation of that number. I think that you should replace the scientifically notated version of the result with the actual result, because the parser doesn't accept scientific notation, giving an error saying the variable 'e' doesn't exist. Eg, evaluate this: 10^100 in the parser and it will give you this: 1e+100. Putting that number back into the parser doesn't work.

**Comment by droptable** [comment]
Good catch!

**Comment by OliverBalfour** [comment]
Cool!
